
export type HybridOutput = { ok:boolean; pages:{page:number;text:string;source:'native'|'ocr';confidence?:number}[]; thumbnails:string[]; fullImages:string[]; isHybrid:boolean }
async function loadPdfJs(){ if((window as any).pdfjsLib) return (window as any).pdfjsLib; await new Promise((res,rej)=>{const s=document.createElement('script'); s.src='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js'; s.onload=()=>res(null); s.onerror=rej; document.head.appendChild(s)}); (window as any).pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js'; return (window as any).pdfjsLib }
async function extractPageText(page:any){ const c=await page.getTextContent(); return c.items.map((i:any)=>i.str).join(' ').trim() }
async function renderPageToCanvas(pdfPage:any, maxWidth=900){ const vp=pdfPage.getViewport({scale:1}); const sc=Math.min(1,maxWidth/vp.width); const svp=pdfPage.getViewport({scale:sc}); const canvas=document.createElement('canvas'); canvas.width=svp.width; canvas.height=svp.height; const ctx=canvas.getContext('2d'); await pdfPage.render({canvasContext:ctx,viewport:svp}).promise; return canvas }
function canvasToBase64(c:HTMLCanvasElement,q=0.6){ return c.toDataURL('image/jpeg',q) }
let ocrReady=false, worker:any=null
async function initOCR(){ if(ocrReady) return; await new Promise((res,rej)=>{const s=document.createElement('script'); s.src='https://cdn.jsdelivr.net/npm/tesseract.js@4/dist/tesseract.min.js'; s.onload=()=>res(null); s.onerror=rej; document.head.appendChild(s)}); const {createWorker}=(window as any).Tesseract; worker=await createWorker({logger:()=>{}}); await worker.load(); await worker.loadLanguage('eng'); await worker.initialize('eng'); ocrReady=true }
function norm(s:string){ return (s||'').replace(/\s+/g,' ').trim() }
export async function processFile(file:File, onStatus:(s:string)=>void): Promise<HybridOutput>{ const pdfjs=await loadPdfJs(); const ab=await file.arrayBuffer(); const pdf=await pdfjs.getDocument({data:ab}).promise; onStatus('Extracting native text...'); const native:any[]=[]; let total=0; for(let i=1;i<=pdf.numPages;i++){ const p=await pdf.getPage(i); const t=await extractPageText(p); native.push({page:i,text:t}); total+=t.length } onStatus('Rendering pages...'); const fullImages:string[]=[]; const thumbnails:string[]=[]; for(let i=1;i<=pdf.numPages;i++){ const p=await pdf.getPage(i); const full=canvasToBase64(await renderPageToCanvas(p,900),0.6); const th=canvasToBase64(await renderPageToCanvas(p,360),0.3); fullImages.push(full); thumbnails.push(th) } const pages:any[]=[]; const avg= total/Math.max(1,pdf.numPages); const threshold=Math.min(80, Math.max(40, Math.round(avg*0.2))); for(let i=0;i<native.length;i++){ const np=native[i]; if(np.text && np.text.length>threshold){ pages.push({page:np.page,text:np.text,source:'native',confidence:100}) } else { onStatus(`OCR page ${np.page}...`); await initOCR(); const res=await worker.recognize(fullImages[i]); pages.push({page:np.page,text:norm(res.data.text),source:'ocr',confidence:res.data.confidence||0}) } } return { ok:true, pages, thumbnails, fullImages, isHybrid: pages.some(p=>p.source==='ocr') } }
